In [115]:
using Oscar

In [116]:
n=2
m=3

R, x, y, lamb = PolynomialRing(QQ, "x" => (1:n+1), "y" => (1:m), "lamb" => (1:m))

f=x[1]-5*x[2]#objective polynomial

g=[x[1]^2-x[2];-x[1]^2+4*x[2];-x[2]+1]#inequality constraints


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

3-element Vector{fmpq_mpoly}:
 x_{1}^2 - x_{2} - y_{1}^2
 -x_{1}^2 + 4*x_{2} - y_{2}^2
 -x_{2} - y_{3}^2 + 1

In [117]:
#compute the set h_sing of polynomials from Fritz John conditions without multiplier of the objective gradient
h_sing=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_sing[i]=x[1]-x[1]
end
for j in 1:m
    for i in 1:n
        h_sing[i]+=lamb[j]*derivative(g[j], i)
    end
end

for j in 1:m
    h_sing=[h_sing;lamb[j]*g[j]]
end

h_sing=[h_sing;1-sum(lamb.^2)]
h=[h;h_sing]

h=[h;x[n+1]-f]#h=(gj(x)-yj^2,h_sing,x_{n+1}-f)

10-element Vector{fmpq_mpoly}:
 x_{1}^2 - x_{2} - y_{1}^2
 -x_{1}^2 + 4*x_{2} - y_{2}^2
 -x_{2} - y_{3}^2 + 1
 2*x_{1}*lamb_{1} - 2*x_{1}*lamb_{2}
 -lamb_{1} + 4*lamb_{2} - lamb_{3}
 x_{1}^2*lamb_{1} - x_{2}*lamb_{1}
 -x_{1}^2*lamb_{2} + 4*x_{2}*lamb_{2}
 -x_{2}*lamb_{3} + lamb_{3}
 -lamb_{1}^2 - lamb_{2}^2 - lamb_{3}^2 + 1
 -x_{1} + 5*x_{2} + x_{3}

In [118]:
RI = radical(ideal(R, h))
#RI = ideal(R, h)
gens(RI)

9-element Vector{fmpq_mpoly}:
 lamb_{3}
 lamb_{1} - 4*lamb_{2}
 y_{2}
 y_{1}
 x_{3}
 x_{2}
 x_{1}
 17*lamb_{2}^2 - 1
 y_{3}^2 - 1

In [119]:
G=groebner_basis(RI)

9-element Vector{fmpq_mpoly}:
 lamb_{3}
 lamb_{1} - 4*lamb_{2}
 y_{2}
 y_{1}
 x_{3}
 x_{2}
 x_{1}
 17*lamb_{2}^2 - 1
 y_{3}^2 - 1

In [120]:
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+1,n+1))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

h_uni# generators of the image f(S(g)\cap C(g))

1-element Vector{fmpq_mpoly}:
 x_{3}