In [163]:
using Oscar

In [154]:
function solve_FJ(n,m,f,g,h,R,x,lamb,t;radical_comp=true)

@time begin
    
#compute the set h_FJ of polynomials from Fritz John conditions
h_FJ=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_FJ[i]=lamb[1]*derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_FJ[i]-=lamb[j+1]*derivative(g[j], i)
    end
end

for j in 1:m
    h_FJ=[h_FJ;lamb[j+1]*g[j]]
end

h_FJ=[h_FJ;1-sum(lamb.^2)]
h=[h;h_FJ]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)

if radical_comp
    RI = radical(ideal(R, h))#compute radical of V(h)
else
    RI = ideal(R, h)
end
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+2,n+2*m+2))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

println(h_uni)# generators of the image f(S(g)\cap V(h_FJ))
    
end
    
end

solve_FJ (generic function with 1 method)

In [137]:
function solve_FJ_plus(n,m,f,g,h,R,x,lamb,t)

@time begin
    
#compute the set h_FJ of polynomials from Fritz John conditions
h_FJ=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_FJ[i]=lamb[1]^2*derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_FJ[i]-=lamb[j+1]^2*derivative(g[j], i)
    end
end

for j in 1:m
    h_FJ=[h_FJ;lamb[j+1]^2*g[j]]
end

h_FJ=[h_FJ;1-sum(lamb.^2)]
h=[h;h_FJ]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)
    
RI = radical(ideal(R, h))#compute radical of V(h)
#RI = ideal(R, h)
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+2,n+2*m+2))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

println(h_uni)# generators of the image f(S(g)\cap V(h_FJ))
    
end
    
end

solve_FJ_plus (generic function with 1 method)

In [86]:
function solve_KKT(n,m,f,g,h,R,x,lamb,t)

@time begin
    
#compute the set h_KKT of polynomials from Karush–Kuhn–Tucker conditions
h_KKT=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_KKT[i]=derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_KKT[i]-=lamb[j]*derivative(g[j], i)
    end
end

for j in 1:m
    h_KKT=[h_KKT;lamb[j]*g[j]]
end

h=[h;h_KKT]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)
    
RI = radical(ideal(R, h))#compute radical of V(h)
#RI = ideal(R, h)
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
#println(G)
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+1,n+2*m+1))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

h_uni# generators of the image f(S(g)\cap V(h_FJ))
    
end
    
end

solve_KKT (generic function with 1 method)

In [162]:
function solve_KKT_plus(n,m,f,g,h,R,x,lamb,t)

@time begin
    
#compute the set h_KKT of polynomials from Karush–Kuhn–Tucker conditions
h_KKT=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_KKT[i]=derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_KKT[i]-=lamb[j]^2*derivative(g[j], i)
    end
end

for j in 1:m
    h_KKT=[h_KKT;lamb[j]^2*g[j]]
end

h=[h;h_KKT]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)
    
RI = radical(ideal(R, h))#compute radical of V(h)
#RI = ideal(R, h)
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
#println(G)
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+1,n+2*m+1))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

h_uni# generators of the image f(S(g)\cap V(h_FJ))
    
end
    
end

solve_KKT_plus (generic function with 1 method)

In [116]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=2

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m+1), "t" => (1:1))

f=x[2]#objective polynomial
g=[-x[1];x[1]-x[2]^2]#inequality constraints


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_FJ(n,m,f,g,h,R,x,lamb,t)

fmpq_mpoly[t_{1}]
  0.014475 seconds (5.60 k allocations: 254.461 KiB, 69.38% compilation time)


In [117]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = u

r = roots(m)

1-element Vector{acb}:
 0

In [118]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=3

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))

f=x[1]-5*x[2]#objective polynomial

g=[x[1]^2-x[2];-x[1]^2+4*x[2];-x[2]+1]#inequality constraints


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_KKT(n,m,f,g,h,R,x,lamb,t)

  0.013323 seconds (40.93 k allocations: 892.672 KiB)


1-element Vector{fmpq_mpoly}:
 100*t_{1}^6 + 1975*t_{1}^5 + 14001*t_{1}^4 + 41395*t_{1}^3 + 39295*t_{1}^2 - 12150*t_{1} + 504

In [119]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 100*u^6 + 1975*u^5 + 14001*u^4 + 41395*u^3 + 39295*u^2 - 12150*u + 504

r = roots(m,isolate_real = true)

6-element Vector{acb}:
 [-7.00000 +/- 3.20e-6]
 [-6.00000 +/- 4.11e-6]
 [-4.00000 +/- 1.24e-6]
 [-3.000000 +/- 5.76e-7]
 [0.050000000 +/- 4.06e-10]
 [0.200000000 +/- 9.30e-10]

In [160]:
# #Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
# using Oscar

# n=2
# m=1

# R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m+1), "t" => (1:1))

# f=(x[1]+1)^2+x[2]^2-1

# g=[x[1]^3-x[2]^2]


# h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

# solve_FJ(n,m,f,g,h,R,x,lamb,t,radical_comp=true)

In [161]:
# CC = ComplexField(64)
# C, u = PolynomialRing(CC, "u")

# m = 27*u^4 + 59*u^3 + 60*u^2 + 28*u

# r = roots(m)

In [149]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=1

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m+1), "t" => (1:1))

f=x[1]-x[2]

g=[(x[1]-x[2])^3]


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_FJ_plus(n,m,f,g,h,R,x,lamb,t)

fmpq_mpoly[t_{1}]
  0.025434 seconds (2.77 k allocations: 96.328 KiB)


In [150]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = u

r = roots(m)

1-element Vector{acb}:
 0

In [122]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=1

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))

f=(x[1]^2+x[2]^2-2)*(x[1]^2+x[2]^2)#objective polynomial

g=[(x[1]^2+x[2]^2-2)*(x[1]-3)]#inequality constraints

h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_KKT(n,m,f,g,h,R,x,lamb,t)

  0.041470 seconds (17.71 k allocations: 785.406 KiB)


1-element Vector{fmpq_mpoly}:
 t_{1}^3 - 62*t_{1}^2 - 63*t_{1}

In [123]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = u^3 - 62*u^2 - 63*u

r = roots(m,isolate_real = true)

3-element Vector{acb}:
 [-1.00000000 +/- 1.40e-9]
 [+/- 6.08e-29]
 [63.00000000 +/- 1.40e-9]

In [131]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=3
m=1

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))

eps=1//10

f=x[1]^4*x[2]^2+x[1]^2*x[2]^4+x[3]^6-3*x[1]^2*x[2]^2*x[3]^2+eps*(x[1]^2+x[2]^2+x[3]^2) 
g=[1-x[1]^2-x[2]^2-x[3]^2]

h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_KKT(n,m,f,g,h,R,x,lamb,t)

  0.166016 seconds (1.48 M allocations: 32.620 MiB, 18.47% gc time)


1-element Vector{fmpq_mpoly}:
 49207500000000000*t_{1}^11 - 81961242187500000*t_{1}^10 + 35401891640625000*t_{1}^9 - 5747811890625000*t_{1}^8 + 576144305156250*t_{1}^7 - 50773802062500*t_{1}^6 + 2487391238125*t_{1}^5 - 34983679000*t_{1}^4 + 1586740350*t_{1}^3 - 4087040*t_{1}^2 + 182336*t_{1}

In [132]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 49207500000000000*u^11 - 81961242187500000*u^10 + 35401891640625000*u^9 - 5747811890625000*u^8 + 576144305156250*u^7 - 50773802062500*u^6 + 2487391238125*u^5 - 34983679000*u^4 + 1586740350*u^3 - 4087040*u^2 + 182336*u

r = roots(m,isolate_real = true)

11-element Vector{acb}:
 [+/- 1.22e-11]
 [0.100000 +/- 2.57e-8]
 [0.1156250 +/- 3.35e-8]
 [0.3500000 +/- 2.03e-8]
 [1.1000000 +/- 1.89e-8]
 [+/- 1.82e-10] + [0.012171612 +/- 5.68e-10]*im
 [+/- 1.22e-10] + [-0.012171612 +/- 5.12e-10]*im
 [+/- 3.29e-10] + [0.024343225 +/- 5.47e-10]*im
 [+/- 3.29e-10] + [-0.024343225 +/- 5.47e-10]*im
 [+/- 1.32e-9] + [0.09737290 +/- 2.18e-9]*im
 [+/- 1.35e-9] + [-0.09737290 +/- 2.21e-9]*im

In [133]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=3

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))


f=x[1]*x[2]+x[1]^3+x[2]^3
g=[x[1];x[2];1-x[1]-x[2]]

h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_KKT(n,m,f,g,h,R,x,lamb,t)

  0.010471 seconds (20.35 k allocations: 447.516 KiB)


1-element Vector{fmpq_mpoly}:
 54*t_{1}^4 - 83*t_{1}^3 + 30*t_{1}^2 - t_{1}

In [134]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 54*u^4 - 83*u^3 + 30*u^2 -u

r = roots(m,isolate_real = true)

4-element Vector{acb}:
 0
 [0.037037037 +/- 1.73e-10]
 [0.50000000 +/- 3.52e-9]
 1.0000000000000000000

In [135]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=3
m=3

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))


f=x[1]^4*x[2]^2+x[2]^4*x[3]^2+x[3]^4*x[1]^2-3*x[1]^2*x[2]^2*x[3]^2
g=[1-x[1]^2;1-x[2]^2;1-x[3]^2]

h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

solve_KKT(n,m,f,g,h,R,x,lamb,t)

  0.564160 seconds (134.99 k allocations: 5.910 MiB)


1-element Vector{fmpq_mpoly}:
 64*t_{1}^4 - 271*t_{1}^3 + 234*t_{1}^2 - 27*t_{1}

In [136]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 64*u^4 - 271*u^3 + 234*u^2 - 27*u

r = roots(m,isolate_real = true)

4-element Vector{acb}:
 [+/- 6.43e-26]
 [0.13616744 +/- 3.33e-9]
 [1.0000000 +/- 6.40e-9]
 [3.09820756 +/- 7.77e-9]

In [151]:
# #Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
# using Oscar

# n=2
# m=3

# R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m+1), "t" => (1:1))


# f=x[1]-1
# g=[x[1];x[2];(x[1]-1)^3-x[2]]

# h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

# solve_FJ_plus(n,m,f,g,h,R,x,lamb,t)

In [152]:
# CC = ComplexField(64)
# C, u = PolynomialRing(CC, "u")

# m = u^2 + u

# r = roots(m,isolate_real = true)