In [48]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=1

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m+1), "t" => (1:1))

f=(x[1]+1)^2+x[2]^2-1#objective polynomial

g=[x[1]^3-x[2]^2]#inequality constraints


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

1-element Vector{fmpq_mpoly}:
 x_{1}^3 - x_{2}^2 - y_{1}^2

In [50]:
@time begin
    
#compute the set h_FJ of polynomials from Fritz John conditions
h_FJ=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_FJ[i]=lamb[1]*derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_FJ[i]-=lamb[j+1]*derivative(g[j], i)
    end
end

for j in 1:m
    h_FJ=[h_FJ;lamb[j+1]*g[j]]
end

h_FJ=[h_FJ;1-sum(lamb.^2)]
h=[h;h_FJ]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)
    
RI = radical(ideal(R, h))#compute radical of V(h)
#RI = ideal(R, h)
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+2,n+2*m+2))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

println(h_uni)# generators of the image f(S(g)\cap V(h_FJ))
    
end

G

fmpq_mpoly[27*t_{1}^4 + 59*t_{1}^3 + 60*t_{1}^2 + 28*t_{1}]
  0.096196 seconds (66.70 k allocations: 3.053 MiB, 47.04% gc time, 39.26% compilation time)


14-element Vector{fmpq_mpoly}:
 27*t_{1}^4 + 59*t_{1}^3 + 60*t_{1}^2 + 28*t_{1}
 27*lamb_{2}*t_{1}^3 + 32*lamb_{2}*t_{1}^2 + 28*lamb_{2}*t_{1}
 9016*lamb_{2}^2 + 14607*t_{1}^4 + 22280*t_{1}^3 + 16689*t_{1}^2 - 9016
 3096*lamb_{1}*t_{1} + 3096*lamb_{1} + 858*lamb_{2}^5*t_{1}^2 + 17668*lamb_{2}^5*t_{1} + 17692*lamb_{2}^5 + 3753*lamb_{2}^3*t_{1}^2 - 24054*lamb_{2}^3*t_{1} - 25170*lamb_{2}^3 - 5736*lamb_{2}*t_{1}^2 + 6386*lamb_{2}*t_{1} + 7478*lamb_{2}
 18576*lamb_{1}*lamb_{2} + 4290*lamb_{2}^4*t_{1}^2 + 74924*lamb_{2}^4*t_{1} + 84332*lamb_{2}^4 + 18765*lamb_{2}^2*t_{1}^2 - 69186*lamb_{2}^2*t_{1} - 107274*lamb_{2}^2 - 28680*t_{1}^2 - 5738*t_{1} + 22942
 lamb_{1}^2 + lamb_{2}^2 - 1
 y_{1}*t_{1} + y_{1}
 y_{1}*lamb_{2}
 300*y_{1}^2 + 6228*lamb_{1}^2*lamb_{2}^2*t_{1}^2 + 7980*lamb_{1}^2*lamb_{2}^2*t_{1} + 1968*lamb_{1}^2*lamb_{2}^2 - 450*lamb_{1}^2*t_{1}^2 - 1950*lamb_{1}^2*t_{1} - 600*lamb_{1}^2 + 1730*lamb_{1}*lamb_{2}^3*t_{1}^2 + 256*lamb_{1}*lamb_{2}^3*t_{1} - 1312*lamb_{1}*lamb_{2}^3 + 1

In [30]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 27*u^4 + 59*u^3 + 60*u^2 + 28*u

r = roots(m)

4-element Vector{acb}:
 [-1.0000000 +/- 5.42e-9]
 [+/- 3.16e-29]
 [-0.5925926 +/- 1.65e-8] + [0.8281733 +/- 3.42e-8]*im
 [-0.5925926 +/- 1.46e-8] + [-0.8281733 +/- 3.26e-8]*im

In [37]:
#Table 1 of ``A symbolic algorithm for exact polynomial optimization strengthened with Fritz John conditions'' by N. H. A. Mai
using Oscar

n=2
m=2

R, x, y, lamb, t = PolynomialRing(QQ, "x" => (1:n), "y" => (1:m), "lamb" => (1:m), "t" => (1:1))

f=x[1]-5*x[2]#objective polynomial

g=[x[1]^2-x[2];-x[1]^2+4*x[2];-x[2]+1]#inequality constraints


h=[g[j]-y[j]^2 for j=1:m]#transform to equality constraints

2-element Vector{fmpq_mpoly}:
 x_{1}^2 - x_{2} - y_{1}^2
 -x_{1}^2 + 4*x_{2} - y_{2}^2

In [41]:
@time begin
    
#compute the set h_KKT of polynomials from Karush–Kuhn–Tucker conditions
h_KKT=Vector{fmpq_mpoly}(undef,n)
for i in 1:n
    h_KKT[i]=derivative(f,i)
end
for j in 1:m
    for i in 1:n
        h_KKT[i]-=lamb[j]*derivative(g[j], i)
    end
end

for j in 1:m
    h_KKT=[h_KKT;lamb[j]*g[j]]
end

h=[h;h_KKT]

h=[h;t[1]-f]#h=(gj(x)-yj^2,h_FJ,x_{n+1}-f)
    
RI = radical(ideal(R, h))#compute radical of V(h)
#RI = ideal(R, h)
#gens(RI)
    
G=groebner_basis(RI, ordering=lex(gens(R)))
    
#println(G)
    
check=1
alpha=zeros(Int64,1)
h_uni=Vector{fmpq_mpoly}([])
for j=1:length(G)
    check=1
    for i in 1:length(G[j])
        alpha=exponent_vector(G[j],i) 
        if sum(alpha[t] for t in setdiff(1:n+2*m+1,n+2*m+1))>0
            check=0
        end
    end
    if check==1
        h_uni=[h_uni;G[j]]
    end
end

h_uni# generators of the image f(S(g)\cap V(h_FJ))
    
end

  0.049033 seconds (51.58 k allocations: 2.806 MiB, 71.49% compilation time)


1-element Vector{fmpq_mpoly}:
 100*t_{1}^2 - 25*t_{1} + 1

In [42]:
CC = ComplexField(64)
C, u = PolynomialRing(CC, "u")

m = 100*u^2 - 25*u + 1

r = roots(m,isolate_real = true)

2-element Vector{acb}:
 [0.0500000000 +/- 7.75e-11]
 [0.200000000 +/- 2.73e-10]